CRITICAL - 2021-02-28 23:52:50 --> There is no data to update.
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(52): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save_questionnaire()
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2021-02-28 23:53:01 --> There is no data to update.
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(52): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save_questionnaire()
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
CRITICAL - 2021-02-28 23:53:10 --> There is no data to update.
#0 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
#1 C:\xampp\htdocs\cbms\app\Controllers\Personnel.php(52): CodeIgniter\Model->update(Array)
#2 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(910): App\Controllers\Personnel->save_questionnaire()
#3 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Personnel))
#4 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\cbms\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 C:\xampp\htdocs\cbms\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(34): require_once('C:\\xampp\\htdocs...')
#7 {main}
